@host=http://127.0.0.1:3000

GET {{host}}/

#### create user
POST {{host}}/create_user
Content-Type: application/json

{
  "username": "testname",
  "password": "asdf",
  "email": "a@e.de"
}

#### auth user
POST {{host}}/auth_user
Content-Type: application/json

{
  "username": "testname",
  "password": "asdf"
}


#### meters_sum
POST {{host}}/get_meters_sum
Content-Type: application/json

{
  "username": "testname"
}